### PR TITLE
Add instructions for required jumpers.

### PR DESCRIPTION
**Pull request by daten**
As mentioned in the blog post at https://cyrusbuilt.net/?p=78 you need to close two jumpers for this code to work.

### CODE REVIEW

**Comment by cyrusbuilt** [comment]
This is subjective and depends on the scenario.  For example, my 632 v2.0 has been working with no jumpers set attached to Arduino Unos and Arduino Megas for years.  The relevant documentation for the hardware can already be found in 632full.pdf.

**Comment by daten** [comment]
That's interesting to know.  I spent a couple evenings scratching my head as to what I was doing wrong before finally guessing you might have published more information somewhere.  Then I found your blog post with the answer.

I had already gone through the PDF at that point, I found the 5V jumper and tried that, but alone I was still getting noise.  It didn't occur to me to try the inverted jumper.

It would have just saved me time personally if there was a hint in the readme about possible jumper changes.  Either way, thanks for your work on this library, it enabled me to use one of the LCD screens I found in my parts bin.

**Comment by cyrusbuilt** [comment]
Thanks! I'm glad someone besides me found it useful.  Hmmm... maybe we just change the text to say something to the effect of "If experiencing noise, try setting JPE and JPB jumpers per the documentation on page blah blah blah..." or something like that.  The behavior may be different on different versions of the hardware or firmware.  Mine is around 20 years old.

**Comment by cyrusbuilt** [comment]
Also, just as an FYI, I intend to implement the additional characters/glyphs in CGROM documented in Appendix C sometime in the near future. So keep an eye on this repo if that is something you'd find useful.

**Comment by cyrusbuilt** [comment]
Fixed this in PR #3

**Pull request closed without merging**
